services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./sql-backups:/sql-backups  # Salin file SQL ke volume ini
    ports:
      - "3005:3005"
    environment:
      - DATABASE_URL=postgresql://postgres:limit123@db:5432/movie-simple  # Gunakan nama service db
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:3005  # Arahkan ke backend service
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - default

  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: limit123
      POSTGRES_DB: movie-simple
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
    driver: bridge  # Gunakan bridge sebagai driver jaringan, biasanya default untuk Docker Compose