import DirectorModel from "../models/DirectorModel";

export const directors: DirectorModel[] = [
  {
    id: 1,
    name: "Tom Hanks",
    birthDate: new Date("1956-07-09"),
    countryCode: "US",
  },
  {
    id: 2,
    name: "Robert De Niro",
    birthDate: new Date("1943-08-17"),
    countryCode: "US",
  },
  {
    id: 3,
    name: "Morgan Freeman",
    birthDate: new Date("1937-06-01"),
    countryCode: "US",
  },
  {
    id: 4,
    name: "Leonardo DiCaprio",
    birthDate: new Date("1974-11-11"),
    countryCode: "US",
  },
  {
    id: 5,
    name: "Brad Pitt",
    birthDate: new Date("1963-12-18"),
    countryCode: "US",
  },
  {
    id: 6,
    name: "Ptityyy",
    birthDate: new Date("1963-12-18"),
    countryCode: "US",
  },
  {
    id: 7,
    name: "Johnny Depp",
    birthDate: new Date("1963-06-09"),
    countryCode: "US",
  },
  {
    id: 8,
    name: "Denzel Washington",
    birthDate: new Date("1954-12-28"),
    countryCode: "US",
  },
  {
    id: 9,
    name: "Will Smith",
    birthDate: new Date("1968-09-25"),
    countryCode: "US",
  },
  {
    id: 10,
    name: "Hugh Jackman",
    birthDate: new Date("1968-10-12"),
    countryCode: "AU",
  },
  {
    id: 11,
    name: "Russell Crowe",
    birthDate: new Date("1964-04-07"),
    countryCode: "ID",
  },
  {
    id: 12,
    name: "Cate Blanchett",
    birthDate: new Date("1969-05-14"),
    countryCode: "AU",
  },
  {
    id: 13,
    name: "Nicole Kidman",
    birthDate: new Date("1967-06-20"),
    countryCode: "AU",
  },
  {
    id: 14,
    name: "Kate Winslet",
    birthDate: new Date("1975-10-05"),
    countryCode: "AZ",
  },
  {
    id: 15,
    name: "Daniel Craig",
    birthDate: new Date("1968-03-02"),
    countryCode: "AZ",
  },
  {
    id: 16,
    name: "Judi Dench",
    birthDate: new Date("1934-12-09"),
    countryCode: "AZ",
  },
  {
    id: 17,
    name: "Emma Watson",
    birthDate: new Date("1990-04-15"),
    countryCode: "AZ",
  },
  {
    id: 18,
    name: "Emma Thompson",
    birthDate: new Date("1959-04-15"),
    countryCode: "AZ",
  },
  {
    id: 19,
    name: "Keira Knightley",
    birthDate: new Date("1985-03-26"),
    countryCode: "AZ",
  },
  {
    id: 20,
    name: "Meryl Streep",
    birthDate: new Date("1949-06-22"),
    countryCode: "US",
  },
  {
    id: 21,
    name: "Julia Roberts",
    birthDate: new Date("1967-10-28"),
    countryCode: "US",
  },
  {
    id: 22,
    name: "Sandra Bullock",
    birthDate: new Date("1964-07-26"),
    countryCode: "US",
  },
  {
    id: 23,
    name: "Scarlett Johansson",
    birthDate: new Date("1984-11-22"),
    countryCode: "US",
  },
  {
    id: 24,
    name: "Scarlett Wasingsong",
    birthDate: new Date("1984-11-22"),
    countryCode: "US",
  },
  {
    id: 25,
    name: "Jennifer Lawrence",
    birthDate: new Date("1990-08-15"),
    countryCode: "US",
  },
];
